import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Nextjs 14 crash",
  description: "Generated by create next-14 app",
  keywords: "webdeve, js, nextjs, reactjs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
